### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by gkazanci** [reddec/syno-cli#14]
Hello, I am not a very professional user. I am using docker for the first time. I tried to do the steps properly and I am getting timepout error as below. I'll be happy if you can help me. Thanks.

![Ekran görüntüsü 2024-07-18 112234](https://github.com/user-attachments/assets/52f7da78-a491-43c2-a08f-f1a218213264)

![Ekran görüntüsü 2024-07-18 131339_Aaaa](https://github.com/user-attachments/assets/d24e0350-6176-4426-8707-60c1342d2f51)

**Comment by reddec** [comment]
Hi!
Thanks for the question. Could you please copy log messages here (please remove sensitive information if ever)? 
<img width="727" alt="image" src="https://github.com/user-attachments/assets/a38eaa22-7c30-42d1-a6e1-128652d56dd6">

**Comment by gkazanci** [comment]
syno-cli
date	stream	content
2024/07/18 11:22:00	stdout	get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get "https://acme-v02.api.letsencrypt.org/directory": dial tcp: lookup acme-v02.api.letsencrypt.org on 192.168.1.56:53: read udp 172.17.0.2:47646->192.168.1.56:53: i/o timeout
2024/07/18 11:21:50	stdout	2024/07/18 08:21:50 generating new account
2024/07/18 10:04:41	stdout	get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get "https://acme-v02.api.letsencrypt.org/directory": dial tcp: lookup acme-v02.api.letsencrypt.org on 192.168.1.56:53: read udp 172.17.0.2:51400->192.168.1.56:53: i/o timeout
2024/07/18 10:04:31	stdout	2024/07/18 07:04:31 generating new account

**Comment by reddec** [comment]
@gkazanci thanks for logs. Please check that NAS has an access to internet: it might be problem in physical connection (ex cable somewhere got detached) or transport level (ex: firewall or routing).

How to check: 

1. log-in via ssh to NAS
2. execute `curl -v https://example.com`. If it will not work, then something with NAS internet in general.
3. do the same but via docker container. If previous worked and this not, then there is problem with your docker installation. The simplest solution will to reinstall containers manager and restart NAS.


P.S

before debugging just restart NAS, it might help

**Comment by gkazanci** [comment]
Hello, thank you, disabling the Synology firewall fixed it. I blocked the connection from outside my country for security reasons. I think that's why it happened.

But I haven't been able to generate a certificate yet. :)
I'm currently getting an error like this. Could it be because I tried too hard?

2024/07/19 08:20:37 done, next check after 1 hour
2024/07/19 11:20:37 stdout 2024/07/19 08:20:37 failed push to Synology: login: invoke api: get API SYNO.API.Auth version: invoke api: execute request: Post "http: //172.17.0.1:5000/webapi/query.cgi?": dial tcp 172.17.0.1:5000: connect: connection refused

**Comment by gkazanci** [comment]
Hello, I reinstalled. The log was created as shown in the attachment. When I look at the certificate section, the certificate has not been created yet.


syno-cli2
date	stream	content
2024/07/19 12:05:58	stdout	2024/07/19 09:05:58 done, next check after 1 hour
2024/07/19 12:05:58	stdout	2024/07/19 09:05:58 failed push to Synology: login: invoke api: get API SYNO.API.Auth version: invoke api: execute request: Post "http://172.17.0.1:5000/webapi/query.cgi?": dial tcp 172.17.0.1:5000: connect: connection refused
2024/07/19 12:05:58	stdout	2024/07/19 09:05:58 [INFO] [*.ikonproje.com] Server responded with a certificate.
2024/07/19 12:05:56	stdout	2024/07/19 09:05:56 [INFO] [*.ikonproje.com] acme: Validations succeeded; requesting certificates
2024/07/19 12:05:55	stdout	2024/07/19 09:05:55 [INFO] [*.ikonproje.com] acme: Cleaning DNS-01 challenge
2024/07/19 12:05:55	stdout	2024/07/19 09:05:55 [INFO] [*.ikonproje.com] The server validated our request
2024/07/19 12:05:49	stdout	2024/07/19 09:05:49 [INFO] [*.ikonproje.com] acme: Waiting for DNS record propagation.
2024/07/19 12:05:47	stdout	2024/07/19 09:05:47 [INFO] [*.ikonproje.com] acme: Waiting for DNS record propagation.
2024/07/19 12:05:47	stdout	2024/07/19 09:05:47 [INFO] Wait for propagation [timeout: 2m0s, interval: 2s]
2024/07/19 12:05:45	stdout	2024/07/19 09:05:45 [INFO] [*.ikonproje.com] acme: Checking DNS record propagation using [8.8.8.8:53]
2024/07/19 12:05:45	stdout	2024/07/19 09:05:45 [INFO] [*.ikonproje.com] acme: Trying to solve DNS-01
2024/07/19 12:05:45	stdout	2024/07/19 09:05:45 [INFO] cloudflare: new record for ikonproje.com, ID dedb67999ab7dfc74a70f2dac911f100
2024/07/19 12:05:43	stdout	2024/07/19 09:05:43 [INFO] [*.ikonproje.com] acme: Preparing to solve DNS-01
2024/07/19 12:05:43	stdout	2024/07/19 09:05:43 [INFO] [*.ikonproje.com] acme: use dns-01 solver
2024/07/19 12:05:43	stdout	2024/07/19 09:05:43 [INFO] [*.ikonproje.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/379004550717
2024/07/19 12:05:42	stdout	2024/07/19 09:05:42 [INFO] [*.ikonproje.com] acme: Obtaining bundled SAN certificate
2024/07/19 12:05:42	stdout	2024/07/19 09:05:42 issuing new certificate for domain *.ikonproje.com
2024/07/19 12:05:42	stdout	2024/07/19 09:05:42 issuing or renewing certificates if needed
2024/07/19 12:05:42	stdout	2024/07/19 09:05:42 start initial setup
2024/07/19 12:05:42	stdout	2024/07/19 09:05:42 setting challenger for cloudflare
2024/07/19 12:05:40	stdout	2024/07/19 09:05:40 generating new account

**Comment by gkazanci** [comment]
I gave an externally accessible domain address to the synology url address section. In this case, I get an error as follows.


2024/07/19 13:05:10 | stdout | 2024/07/19 10:05:10 failed push to Synology: login: invoke api: response: API error code: 406
2024/07/19 13:05:09 | stdout | 2024/07/19 10:05:09 issuing or renewing certificates if needed
2024/07/19 13:05:09 | stdout | 2024/07/19 10:05:09 start initial setup
2024/07/19 13:05:09 | stdout | 2024/07/19 10:05:09 setting challenger for cloudflare
2024/07/19 13:05:09 | stdout | 2024/07/19 10:05:09 using saved account

**Comment by gkazanci** [comment]
everything is ok. thanks a lot.
