### ISSUE TITLE
ignore HTTPS warning

### ISSUE THREAD

**Issue by Stunt0265** [reddec/syno-cli#6]
Is there a way to use the "-insecure" flag to ignore a bad SSL cert when using a https URL?

**Comment by reddec** [comment]
My bad, I forgot to add this option.
It's very easy to add. I'll do it if no one else will take it before.

**Comment by reddec** [comment]
@Stunt0265 Should be fixed in [v0.1.3](https://github.com/reddec/syno-cli/releases/tag/v0.1.3)

**Comment by Stunt0265** [comment]
Thanks.  Can you expand on the environmental variables to use?  I'm getting an error "Please specify the cert command".  I also see a new "URL" variable in addition to the "SYNOLOGY_URL" one.  And should the new variable be "SYNOLOGY_INSECURE" and set to "true" if wanting to use it?
